## Upload dataset

In [1]:
import pandas as pd
import numpy as np

#For visualizations
import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

from mlxtend.preprocessing import minmax_scaling


import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv("heart.csv", index_col = 0)
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [5]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
195,54.0,0.0,4.0,127.0,333,1,1,154,0,0,?,?,?,1
196,62.0,1.0,1.0,120.0,139,0,1,?,?,?,?,?,?,0
197,55.0,1.0,4.0,122.0,223,1,1,100,0,0,?,?,6,2
198,58.0,1.0,4.0,120.0,385,1,2,?,?,?,?,?,?,0
199,62.0,1.0,2.0,120.0,254,0,2,93,1,0,?,?,?,1

## Finding null and missing values

In [7]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
df.dtypes

age         float64
sex         float64
cp          float64
trestbps    float64
chol         object
fbs          object
restecg      object
thalach      object
exang        object
oldpeak      object
slope        object
ca           object
thal         object
target        int64
dtype: object

## Scaling and Normalizing Data

In [9]:
age = pd.DataFrame(df.age)
cp = pd.DataFrame(df.cp)
trestbps = pd.DataFrame(df.trestbps)
chol = pd.DataFrame(df.chol)
fbs = pd.DataFrame(df.fbs)
restecg = pd.DataFrame(df.restecg)
thalach = pd.DataFrame(df.thalach)
exang = pd.DataFrame(df.exang)
oldpeak = pd.DataFrame(df.oldpeak)
slope = pd.DataFrame(df.slope)
ca = pd.DataFrame(df.ca)
thal = pd.DataFrame(df.thal)

In [10]:
age_scaled = minmax_scaling(age, columns=['age'])
cp_scaled = minmax_scaling(cp, columns=['cp'])
trestbps_scaled = minmax_scaling(trestbps, columns=['trestbps'])
chol_scaled = minmax_scaling(chol, columns=['chol'])
fbs_scaled = minmax_scaling(fbs, columns=['fbs'])
restecg_scaled = minmax_scaling(restecg, columns=['restecg'])
thalach_scaled = minmax_scaling(thalach, columns=['thalach'])
exang_scaled = minmax_scaling(exang, columns=['exang'])
oldpeak_scaled = minmax_scaling(oldpeak, columns=['oldpeak'])
slope_scaled = minmax_scaling(slope, columns=['slope'])
ca_scaled = minmax_scaling(ca, columns=['ca'])
thal_scaled = minmax_scaling(thal, columns=['thal'])


data = {'age' : age_scaled.age, 'sex': df.sex,  'cp' : cp_scaled.cp, 'trestbps': trestbps_scaled.trestbps, 'chol': chol_scaled.chol, 'fbs' : fbs_scaled.fbs, 'restecg' : restecg_scaled.restecg, 'thalach': thalach_scaled.thalach, 'exang': exang_scaled.exang, 'oldpeak': oldpeak_scaled.oldpeak, 'slope': slope_scaled.slope, 'ca': ca_scaled.ca, 'thal' : thal_scaled.thal, 'target': df.target}
scaled_dataset = pd.DataFrame(data)
scaled_dataset

ValueError: could not convert string to float: '?'